project:
  type: book

book:
  title: "search-bug"
  author: "Jane Doe"
  date: "2/17/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo



